import { Room, MarketplaceItem, User } from '@/types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Software engineer from Singapore, moving to London for work',
    verified: true,
    isLeaving: false,
    location: 'Camden',
    moveDate: new Date('2024-02-01'),
    preferences: {
      lifestyle: ['professional', 'quiet', 'clean'],
      budget: { min: 800, max: 1200 },
      duration: '12 months',
    },
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    bio: 'Australian consultant heading back home, need to sell everything',
    verified: true,
    isLeaving: true,
    location: 'Shoreditch',
    preferences: {
      lifestyle: ['social', 'active'],
      budget: { min: 0, max: 0 },
      duration: 'flexible',
    },
  },
  {
    id: '3',
    name: 'Elena Rodriguez',
    email: 'elena@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    bio: 'Spanish teacher, love yoga and cooking',
    verified: true,
    isLeaving: false,
    location: 'Notting Hill',
    preferences: {
      lifestyle: ['active', 'social', 'creative'],
      budget: { min: 700, max: 1000 },
      duration: '6 months',
    },
  },
]

export const mockRooms: Room[] = [
  {
    id: '1',
    title: 'Cozy Double Room in Camden',
    description: 'Beautiful double room in a Victorian house share. Walking distance to Camden Town station. The house has a lovely garden and modern kitchen. Looking for a professional flatmate who enjoys a relaxed atmosphere.',
    price: 950,
    location: 'Camden, NW1',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    available: new Date('2024-02-01'),
    user: mockUsers[1],
    amenities: ['WiFi', 'Garden', 'Washing Machine', 'Dishwasher'],
    roomType: 'private',
    billsIncluded: true,
    deposit: 950,
    minStay: 6,
  },
  {
    id: '2',
    title: 'Modern Studio in Shoreditch',
    description: 'Bright studio apartment in the heart of Shoreditch. Perfect for young professionals. Features a modern kitchenette, ensuite bathroom, and plenty of storage. Great transport links and vibrant neighborhood.',
    price: 1350,
    location: 'Shoreditch, E1',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800',
    ],
    available: new Date('2024-01-20'),
    user: mockUsers[1],
    amenities: ['WiFi', 'Gym', 'Concierge', '24/7 Security'],
    roomType: 'private',
    billsIncluded: false,
    deposit: 1350,
    minStay: 12,
  },
  {
    id: '3',
    title: 'Spacious Room in Notting Hill',
    description: 'Large double room in a beautiful period property. Share with 2 other professionals. The flat has high ceilings, original features, and is newly renovated. Close to Portobello Market.',
    price: 1100,
    location: 'Notting Hill, W11',
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800',
    ],
    available: new Date('2024-02-15'),
    user: mockUsers[0],
    amenities: ['WiFi', 'Cleaner', 'Washing Machine', 'Central Heating'],
    roomType: 'private',
    billsIncluded: true,
    deposit: 1100,
    minStay: 6,
  },
  {
    id: '4',
    title: 'Affordable Room in Zone 2',
    description: 'Great value room in a friendly house share. Perfect for someone new to London. Close to tube station and local amenities. Current flatmates are professionals in their 20s-30s.',
    price: 750,
    location: 'Stratford, E15',
    images: [
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800',
    ],
    available: new Date('2024-01-25'),
    user: mockUsers[2],
    amenities: ['WiFi', 'Washing Machine', 'Shared Garden'],
    roomType: 'private',
    billsIncluded: true,
    deposit: 750,
    minStay: 3,
  },
  {
    id: '5',
    title: 'Luxury Ensuite in Canary Wharf',
    description: 'Premium ensuite room in a modern apartment with stunning river views. Building amenities include gym, cinema room, and roof terrace. Perfect for banking/finance professionals.',
    price: 1450,
    location: 'Canary Wharf, E14',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    available: new Date('2024-02-10'),
    user: mockUsers[1],
    amenities: ['WiFi', 'Gym', 'Concierge', 'Roof Terrace', 'Cinema Room'],
    roomType: 'private',
    billsIncluded: false,
    deposit: 1450,
    minStay: 12,
  },
]

export const mockMarketplaceItems: MarketplaceItem[] = [
  {
    id: '1',
    title: 'IKEA Sofa - Excellent Condition',
    description: '3-seater grey sofa from IKEA. Only 8 months old, barely used. Very comfortable and in excellent condition. Selling because relocating back to Australia.',
    price: 150,
    category: 'Furniture',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    location: 'Shoreditch, E1',
    user: mockUsers[1],
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    title: 'Desk & Office Chair Set',
    description: 'White desk (120x60cm) and ergonomic office chair. Perfect for home office setup. Chair has adjustable height and lumbar support.',
    price: 80,
    category: 'Furniture',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1551815113-5d8c91e2e9a6?w=800',
    ],
    location: 'Camden, NW1',
    user: mockUsers[1],
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    title: 'Kitchen Essentials Bundle',
    description: 'Complete kitchen starter pack: pots, pans, cutlery, plates, glasses, utensils. Everything you need to start cooking! All items cleaned and in good condition.',
    price: 45,
    category: 'Kitchen',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800',
    ],
    location: 'Notting Hill, W11',
    user: mockUsers[0],
    createdAt: new Date('2024-01-08'),
  },
  {
    id: '4',
    title: 'Queen Size Bed Frame & Mattress',
    description: 'Comfortable queen bed with mattress. Frame is solid wood, mattress is memory foam (1 year old). Clean and well-maintained.',
    price: 200,
    category: 'Furniture',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
    ],
    location: 'Shoreditch, E1',
    user: mockUsers[1],
    createdAt: new Date('2024-01-11'),
  },
  {
    id: '5',
    title: 'Standing Lamp - Modern Design',
    description: 'Stylish floor lamp with adjustable head. Perfect for reading corner or office. Gold finish with white shade.',
    price: 30,
    category: 'Decor',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800',
    ],
    location: 'Camden, NW1',
    user: mockUsers[1],
    createdAt: new Date('2024-01-09'),
  },
  {
    id: '6',
    title: 'Microwave Oven - 800W',
    description: 'Samsung microwave in perfect working condition. 800W, 20L capacity. Great for quick meals and reheating.',
    price: 40,
    category: 'Appliances',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=800',
    ],
    location: 'Notting Hill, W11',
    user: mockUsers[0],
    createdAt: new Date('2024-01-13'),
  },
]
